// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE5H8jKTbcKWDyQ5MdejFDAIAJQFcnBa0',
    appId: '1:589876122141:web:1217003465bc239541ecf4',
    messagingSenderId: '589876122141',
    projectId: 'cinma-ffcdd',
    authDomain: 'cinma-ffcdd.firebaseapp.com',
    storageBucket: 'cinma-ffcdd.appspot.com',
    measurementId: 'G-XS8SSDC0K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL-gnSx_NmxNtZ-LiUOqUtPNXEE9p_Z3s',
    appId: '1:589876122141:android:04158a627ff46c9241ecf4',
    messagingSenderId: '589876122141',
    projectId: 'cinma-ffcdd',
    storageBucket: 'cinma-ffcdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_7kpreGSls95eoB_6wEIW7K1Ufz35BM',
    appId: '1:589876122141:ios:c4d4488e4f22980541ecf4',
    messagingSenderId: '589876122141',
    projectId: 'cinma-ffcdd',
    storageBucket: 'cinma-ffcdd.appspot.com',
    iosBundleId: 'com.example.fantasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL_7kpreGSls95eoB_6wEIW7K1Ufz35BM',
    appId: '1:589876122141:ios:c4d4488e4f22980541ecf4',
    messagingSenderId: '589876122141',
    projectId: 'cinma-ffcdd',
    storageBucket: 'cinma-ffcdd.appspot.com',
    iosBundleId: 'com.example.fantasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE5H8jKTbcKWDyQ5MdejFDAIAJQFcnBa0',
    appId: '1:589876122141:web:a0255cc1b777c0f841ecf4',
    messagingSenderId: '589876122141',
    projectId: 'cinma-ffcdd',
    authDomain: 'cinma-ffcdd.firebaseapp.com',
    storageBucket: 'cinma-ffcdd.appspot.com',
    measurementId: 'G-Y75FCGKSBZ',
  );
}
